### ISSUE TITLE
docker-machine RAM

### ISSUE THREAD

**Issue by technowar** [wadiwasi/btg#20]
I suggest using `2048 MB` of RAM instead of `1024 MB`. I have errors with `docker ps` and cannot continue with `docker-compose up`.

Using `2048 MB` fixed my problem. However, if `1024 MB` works for you, you may skip this shit.

`docker-machine create -d virtualbox --virtualbox-memory "2048" dev`

**Comment by elizar** [comment]
agreed :+1:

**Comment by elizar** [comment]
I add nis README jom2x

**Comment by elizar** [comment]
CC @technowar

**Comment by XanderDwyl** [comment]
agreed :+1:

**Comment by technowar** [comment]
Already added to pr #23

**Comment by elizar** [comment]
Btw, if you guys want to reference issues from your pull-requests, just include the issue number after the `#` sign in your commit message.

**Comment by elizar** [comment]
i.e

```
Sample commit message
  
    This closes #31337

```

**Comment by technowar** [comment]
Pr #23 merged. Now closing.
