### ISSUE TITLE
Permission to post Wiki

### ISSUE THREAD

**Issue by technowar** [wadiwasi/btg#49]
Can I please haz permission to post Wiki.

**Comment by XanderDwyl** [comment]
can you elaborate if further?

**Comment by technowar** [comment]
I'd like to create a Wiki page for BTG, but can't since I don't have access.

**Comment by elizar** [comment]
> I'd like to create a Wiki page for BTG, but can't since I don't have access.

_DONE!_

**Comment by elizar** [comment]
CC @technowar @wadiwasi/wadiwasi
